### ISSUE TITLE
instapack 8 TODO

### ISSUE THREAD

**Issue by ryanelian** [ryanelian/instapack#601]
- [x] TypeScript-ESLint integration #394 

- [x] Change `silent` global setting to `mute`

- [x] Change `hot` flag to `serve`

- [x] Change `nodebug` flag to `no-sourcemaps`

- [x] Enable hidden source maps on production mode build.

- [x] Allow translation of an array of TypeScript paths to an array of webpack aliases: https://github.com/webpack/webpack/issues/6817 (should notify user when this happens) ~~This is blocked by webpack Type Definition. (`@types/webpack@4` Alias does not allow array unlike version 5 https://github.com/webpack/webpack/blob/master/declarations/WebpackOptions.d.ts#L749)~~

- [x] Enable HTTPS on Webpack Dev Server #507 

- [x] ~~Configure `html-loader` options.~~ Revert to instapack classic template loader for back-compat and accurate source mapping, but dropped `.vue.html` file compilation.

- [x] Allow Copy Overwrite using `--cow` flag when using copy build tool.

- [x] For the love of God, simplify variables loading. Adding build flag / project options to instapack should not make me edit 6 files.

- [x] Auto download mkcert if not available on Windows OS Path, store in user instapack folder.

- [x] Force package restore using npm if `package-lock.json` exists.

    - Then force package restore using yarn if `yarn.lock` exists.
- [x] Bug report to vue loader about HTML loader order breaking build.

    - Tracking this issue at https://github.com/vuejs/vue-loader/issues/1625

- [x] ~~Allow user to explicitly / manually define which libraries in `node_modules` to transpile.~~ Detect and transpile only ES5 libraries...

~~Try switching from clean-css to postcss-csso https://github.com/css/csso~~ (don't fix what's not broken lmao)
