### ISSUE TITLE
instapack 8 stable checklist

### ISSUE THREAD

**Issue by ryanelian** [ryanelian/instapack#712]
instapack codebase is now stable enough for 8.0.0 release but that label will have to wait for these features:

- [x] Webpack 5 https://github.com/webpack/webpack/projects/5

- [x] TypeScript 4.0.0 https://github.com/microsoft/TypeScript/milestone/114

- [x] Vue 3.0.0 https://github.com/vuejs/vue-next/tree/master/packages/compiler-sfc

  - https://github.com/vuejs/vue-class-component/issues/406

- [x] TypeScript-ESLint compatibility with ESLint 7.0.0 https://github.com/typescript-eslint/typescript-eslint/issues/1550

- Modify Vue template to use Web Component.

  - Hit an issue where Shadow DOM cannot be disabled for Vue Web Components using https://github.com/vuejs/vue-web-component-wrapper causing global CSS not applied to components!

  - Alternate custom element library: https://github.com/karol-f/vue-custom-element (has some bugs)

- (Optional) Modify React template to use Web Component.

**Comment by ryanelian** [comment]
There is a flaw in Vue version detection logic in master branch:

When Vue is not yet installed, attempting to read version from `node_modules` will yield `undefined`!

**Comment by ryanelian** [comment]
Released 8.0.0!
